import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Code2 as Github } from "lucide-react";
import { ProjectCard } from "@/components/project-card";
import { Reveal } from "@/components/reveal";
import { SystemDiagram } from "@/components/system-diagram";
import { profile, projects } from "@/lib/content";

export default function Home() {
  return <main id="main">
    <section className="hero shell" aria-labelledby="hero-title">
      <div className="hero-eyebrow mono"><span className="status-dot" /> BACKEND & AI SOFTWARE ENGINEER <span className="hero-edition">PORTFOLIO / 2026</span></div>
      <div className="hero-grid"><div className="hero-copy"><h1 id="hero-title">Built for the<br /><span>real world.</span></h1><p className="hero-intro">I’m Tarun. I build reliable backend systems<br className="desktop-break" /> and turn AI ideas into working software.</p><div className="hero-actions"><Link href="#work" className="button button-primary">Explore my work <ArrowDown size={17} aria-hidden="true" /></Link><a href={profile.github} target="_blank" rel="noopener noreferrer" className="text-link"><Github size={17} aria-hidden="true" /> GitHub <ArrowUpRight size={14} aria-hidden="true" /></a></div></div><SystemDiagram /></div>
      <div className="hero-foot"><span className="mono">CORRECTNESS. CLARITY. CRAFT.</span><p>From the database transaction<br />to the experience it makes possible.</p><Link href="#work" className="scroll-cue" aria-label="Scroll to selected work"><ArrowDown size={19} /></Link></div>
    </section>
    <section id="work" className="section shell" aria-labelledby="work-title"><Reveal><div className="section-heading"><div><span className="eyebrow mono">01 / SELECTED WORK</span><h2 id="work-title">Ideas, engineered.</h2></div><p>A closer look at the systems I build<br />and the decisions behind them.</p></div></Reveal><div className="project-grid">{projects.map(project => <Reveal key={project.slug}><ProjectCard project={project} /></Reveal>)}</div></section>
    <section id="experience" className="section shell experience-section" aria-labelledby="experience-title"><Reveal><div className="section-heading"><div><span className="eyebrow mono">02 / EXPERIENCE</span><h2 id="experience-title">Depth in the details.</h2></div><p>Hands-on experience across backend<br />engineering, AI, and product development.</p></div></Reveal><div className="experience-list">{[{ index: "01", title: "Backend engineering", context: "Independent projects", body: "Transactional systems, event-driven workflows, and APIs designed with failure in mind.", tags: "Java / Spring Boot / PostgreSQL / Kafka", project: projects[0] }, { index: "02", title: "AI evaluation & applied AI", context: "Coursework & software projects", body: "Multimodal model evaluation, reproducible pipelines, and AI-assisted reporting workflows.", tags: "Python / Transformers / FastAPI / Airflow", project: projects[1] }, { index: "03", title: "Full-stack development", context: "Web & mobile projects", body: "Connecting backend services with focused, usable experiences across platforms.", tags: "React / Flask / Android", project: projects[3] }].map(experience => <Reveal key={experience.index}><div className="experience-row"><span className="experience-index mono">{experience.index}</span><div><span className="experience-context mono">{experience.context}</span><h3>{experience.title}</h3><p>{experience.body}</p><span className="experience-tags mono">{experience.tags}</span></div><Link href={`/work/${experience.project.slug}`} className="experience-link" aria-label={`Explore ${experience.title} through ${experience.project.name}`}><ArrowUpRight size={24} /></Link></div></Reveal>)}</div></section>
    <section id="philosophy" className="philosophy-section" aria-labelledby="philosophy-title"><div className="shell"><Reveal><span className="eyebrow mono">03 / ENGINEERING PHILOSOPHY</span><h2 id="philosophy-title">Good software holds up<br /><span>when things don’t.</span></h2></Reveal><div className="principles">{[{ number: "01", title: "Start with the invariants.", body: "Know what must always be true. Put those guarantees in the system, and test the boundaries." }, { number: "02", title: "Make complexity earn its place.", body: "Clear interfaces. Explicit tradeoffs. The simplest architecture that serves the problem well." }, { number: "03", title: "Measure what matters.", body: "A convincing demo is a starting point. Useful evaluation looks at failure modes and makes uncertainty visible." }].map(principle => <Reveal key={principle.number}><div className="principle"><span className="mono">{principle.number}</span><h3>{principle.title}</h3><p>{principle.body}</p></div></Reveal>)}</div></div></section>
    <section id="about" className="section shell about-section" aria-labelledby="about-title"><Reveal><span className="eyebrow mono">04 / A LITTLE ABOUT ME</span><h2 id="about-title">Curious by default.<br />Engineer by choice.</h2></Reveal><Reveal className="about-copy"><p>I’m Tarun Bagewadi, a software engineer focused on backend systems and applied AI. I’m drawn to the space where a promising idea becomes something dependable.</p><p>My work spans transaction ledgers, multimodal evaluation, AI workflows, and full-stack applications. The thread through all of it: understanding how things work, asking where they can fail, and making the next version better.</p><div className="about-signature"><span className="mono">MY KIND OF PROBLEM</span><span><Check size={16} aria-hidden="true" /> Technically challenging. Useful to someone.</span></div></Reveal></section>
    <section id="contact" className="contact-section shell" aria-labelledby="contact-title"><Reveal><div className="contact-top"><span className="eyebrow mono">05 / WHAT’S NEXT?</span><span className="mono contact-note">GOOD CONVERSATIONS BUILD GOOD THINGS.</span></div><div className="contact-main"><h2 id="contact-title">Let’s build<br /><span>something that lasts.</span></h2><a className="contact-arrow" href={`mailto:${profile.email}`} aria-label={`Email Tarun at ${profile.email}`}><ArrowUpRight size={44} strokeWidth={1.2} /></a></div><div className="contact-bottom"><p>Have an engineering role, a project, or an interesting problem?</p><a href={`mailto:${profile.email}`}>{profile.email}<ArrowRight size={18} aria-hidden="true" /></a></div></Reveal></section>
  </main>;
}
